apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gati-tech-network-policy
  namespace: gati-tech-prod
spec:
  podSelector:
    matchLabels:
      app: gati-tech-ams
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 27017
