apiVersion: v1
kind: Secret
metadata:
  name: gati-tech-secrets
  namespace: gati-tech-prod
  labels:
    app: gati-tech-ams
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://<username>:<password>@cluster0.xxxxx.mongodb.net/gati-tech-ams?retryWrites=true&w=majority"
  NEXTAUTH_SECRET: "<generate-with-openssl-rand-base64-32>"
  REDIS_PASSWORD: "<redis-password>"
  AWS_ACCESS_KEY_ID: "<aws-access-key>"
  AWS_SECRET_ACCESS_KEY: "<aws-secret-key>"
  AWS_S3_BUCKET: "gati-tech-assets"
